import { RatioType } from "./graphql";

export const origworld = {
    name: 'A Nice World 2',
    logo: 'icones/ecolo.jpg',
    money: 0,
    score: 0,
    totalangels: 0,
    activeangels: 0,
    angelbonus: 2,
    lastupdate: 0,
    products: [
        {
            id: 1,
            name: 'Des bonbons !!',
            logo: 'icones/bonbons.jpg',
            cout: 4,
            croissance: 1.07,
            revenu: 1,
            vitesse: 500,
            quantite: 1,
            timeleft: 0,
            managerUnlocked: false,
            paliers: [
                {
                    name: 'Une poignée de bonbons !',
                    logo: 'icones/bonbons.jpg',
                    seuil: 10,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
                {
                    name: "Une sac de bonbons !!",
                    logo: 'icones/bonbons.jpg',
                    seuil: 100,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
                {
                    name: "Une montagne de bonbons !!!",
                    logo: 'icones/bonbons.jpg',
                    seuil: 1000,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
            ],
        },
        {
            id: 2,
            name: 'Des chocolats !!',
            logo: 'icones/chocolats.jpg',
            cout: 4,
            croissance: 1.07,
            revenu: 1,
            vitesse: 500,
            quantite: 1,
            timeleft: 0,
            managerUnlocked: false,
            paliers: [
                {
                    name: 'Une poignée de chocolats !',
                    logo: 'icones/chocolats.jpg',
                    seuil: 10,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
                {
                    name: "Une sac de chocolats !!",
                    logo: 'icones/chocolats.jpg',
                    seuil: 100,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
                {
                    name: "Une montagne de chocolats !!!",
                    logo: 'icones/chocolats.jpg',
                    seuil: 1000,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
            ],
        },
        {
            id: 3,
            name: 'Une barbe à papa !!',
            logo: 'icones/barbapapa.jpg',
            cout: 4,
            croissance: 1.07,
            revenu: 1,
            vitesse: 500,
            quantite: 1,
            timeleft: 0,
            managerUnlocked: false,
            paliers: [
                {
                    name: 'Comme un petit nuage !',
                    logo: 'icones/barbapapa.jpg',
                    seuil: 10,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
                {
                    name: "Une sac de chocolats !!",
                    logo: 'icones/barbapapa.jpg',
                    seuil: 100,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
                {
                    name: "Une montagne de chocolats !!!",
                    logo: 'icones/barbapapa.jpg',
                    seuil: 1000,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
            ],
        },
    ]
}