import { RatioType } from "./graphql";

export const origworld = {
    name: 'A Nice World 2',
    logo: 'icones/ecolo.jpg',
    money: 0,
    score: 0,
    totalangels: 0,
    activeangels: 0,
    angelbonus: 2,
    lastupdate: 0,
    products: [
        {
            id: 1,
            name: 'Des bonbons !!',
            logo: 'icones/bonbons.jpg',
            cout: 3,
            croissance: 1.03,
            revenu: 1,
            vitesse: 500,
            quantite: 1,
            timeleft: 0,
            managerUnlocked: false,
            paliers: [
                {
                    name: 'Une poignée de bonbons !',
                    logo: 'icones/bonbons.jpg',
                    seuil: 10,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
                {
                    name: "Une sac de bonbons !!",
                    logo: 'icones/bonbons.jpg',
                    seuil: 100,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
                {
                    name: "Une montagne de bonbons !!!",
                    logo: 'icones/bonbons.jpg',
                    seuil: 1000,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
            ],
        },
        {
            id: 2,
            name: 'Des chocolats !!',
            logo: 'icones/chocolats.jpg',
            cout: 5,
            croissance: 1.07,
            revenu: 3,
            vitesse: 1000,
            quantite: 0,
            timeleft: 0,
            managerUnlocked: false,
            paliers: [
                {
                    name: 'Une poignée de chocolats !',
                    logo: 'icones/chocolats.jpg',
                    seuil: 10,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
                {
                    name: "Une sac de chocolats !!",
                    logo: 'icones/chocolats.jpg',
                    seuil: 100,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
                {
                    name: "Une montagne de chocolats !!!",
                    logo: 'icones/chocolats.jpg',
                    seuil: 1000,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
            ],
        },
        {
            id: 3,
            name: 'Une barbe à papa !!',
            logo: 'icones/barbapapa.jpg',
            cout: 8,
            croissance: 1.12,
            revenu: 5,
            vitesse: 1750,
            quantite: 0,
            timeleft: 0,
            managerUnlocked: false,
            paliers: [
                {
                    name: 'Comme un petit nuage !',
                    logo: 'icones/barbapapa.jpg',
                    seuil: 10,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
                {
                    name: "Une sac de chocolats !!",
                    logo: 'icones/barbapapa.jpg',
                    seuil: 100,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
                {
                    name: "Une montagne de chocolats !!!",
                    logo: 'icones/barbapapa.jpg',
                    seuil: 1000,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
            ],
        },
        {
            id: 4,
            name: 'Glaces !!',
            logo: 'icones/barbapapa.jpg',
            cout: 15,
            croissance: 1.12,
            revenu: 8,
            vitesse: 2500,
            quantite: 0,
            timeleft: 0,
            managerUnlocked: false,
            paliers: [
                {
                    name: 'Comme un petit nuage !',
                    logo: 'icones/barbapapa.jpg',
                    seuil: 10,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
                {
                    name: "Une sac de chocolats !!",
                    logo: 'icones/barbapapa.jpg',
                    seuil: 100,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
                {
                    name: "Une montagne de chocolats !!!",
                    logo: 'icones/barbapapa.jpg',
                    seuil: 1000,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
            ],
        },
        {
            id: 5,
            name: 'Un Panckake !!',
            logo: 'icones/barbapapa.jpg',
            cout: 25,
            croissance: 1.08,
            revenu: 13,
            vitesse: 5000,
            quantite: 0,
            timeleft: 0,
            managerUnlocked: false,
            paliers: [
                {
                    name: 'Comme un petit nuage !',
                    logo: 'icones/barbapapa.jpg',
                    seuil: 10,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
                {
                    name: "Une sac de chocolats !!",
                    logo: 'icones/barbapapa.jpg',
                    seuil: 100,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
                {
                    name: "Une montagne de chocolats !!!",
                    logo: 'icones/barbapapa.jpg',
                    seuil: 1000,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
            ],
        },
        {
            id: 6,
            name: 'Un Paris-Brest !!',
            logo: 'icones/barbapapa.jpg',
            cout: 35,
            croissance: 1.05,
            revenu: 20,
            vitesse: 10000,
            quantite: 0,
            timeleft: 0,
            managerUnlocked: false,
            paliers: [
                {
                    name: 'Comme un petit nuage !',
                    logo: 'icones/barbapapa.jpg',
                    seuil: 10,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
                {
                    name: "Une sac de chocolats !!",
                    logo: 'icones/barbapapa.jpg',
                    seuil: 100,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
                {
                    name: "Une montagne de chocolats !!!",
                    logo: 'icones/barbapapa.jpg',
                    seuil: 1000,
                    idcible: 1,
                    ratio: 2,
                    typeratio: RatioType.vitesse,
                    unlocked: false,
                },
            ],
        },
    ],
    allunlocks: [
        {
            name: 'All is better than one',
            logo: 'icones/all.jpg',
            seuil: 30,
            idcible: 0,
            ratio: 2,
            typeratio: RatioType.gain,
            unlocked: false,
        },
        {
            name: 'To take and not to give',
            logo: 'icones/all.jpg',
            seuil: 150,
            idcible: 0,
            ratio: 3,
            typeratio: RatioType.gain,
            unlocked: false,
        }
    ],
    upgrades: [
        {
            name: 'Do you like paper bag ?',
            logo: 'icones/sacpapier.jpg',
            seuil: 1000,
            idcible: 1,
            ratio: 3,
            typeratio: RatioType.gain,
            unlocked: false,
        },
        {
            name: 'This is my bin',
            logo: 'icones/recyclage.jpg',
            seuil: 15000,
            idcible: 2,
            ratio: 3,
            typeratio: RatioType.gain,
            unlocked: false,
        },
    ],
    angelupgrades: [
        {
            name: 'Angel Sacrifice',
            logo: 'icones/angel.png',
            seuil: 10,
            idcible: 0,
            ratio: 3,
            typeratio: RatioType.gain,
            unlocked: false,
        },
        {
            name: 'Angelic Mutiny',
            logo: 'icones/angel.png',
            seuil: 100000,
            idcible: -1,
            ratio: 2,
            typeratio: RatioType.ange,
            unlocked: false,
        },
    ],
    managers: [
        {
            name: 'Wangari Maathai',
            logo: 'icones/WangariMaathai.jpg',
            seuil: 10,
            idcible: 1,
            ratio: 0,
            typeratio: RatioType.gain,
            unlocked: false,
        },
        {
            name: 'Ellen MacArthur',
            logo: 'icones/ellenmacarthur.jpg',
            seuil: 15000,
            idcible: 2,
            ratio: 0,
            typeratio: RatioType.gain,
            unlocked: false,
        }
    ],
};
